name: Build and Push + Update GitOps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout App Repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: sagarbindudash/devops-app:${{ github.run_number }}

      #  Clone GitOps repo
      - name: Clone GitOps Repo
        run: |
          git clone https://github.com/sagarbindu/End-2-end-gitops.git

      #  Update Helm values.yaml
      - name: Update Image Tag
        run: |
          cd devops-gitops
          sed -i 's/tag:.*/tag: "${{ github.run_number }}"/' values.yaml

      #  Commit and push
      - name: Push changes
        run: |
          cd devops-gitops
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update image tag to ${{ github.run_number }}"
          git push https://${{ secrets.GIT_TOKEN }}@github.com/sagarbindudash/devops-gitops.git
